import type { Metadata, MetadataRoute } from "next"

import { isIndexable, siteConfig } from "@/lib/site"

/*
 * Every public route is registered here once. The entry drives the page's
 * <title>, description, canonical URL, Open Graph and Twitter tags (through
 * createMetadata), its sitemap.xml row, its llms.txt line and its JSON-LD, so
 * those can never disagree with each other.
 *
 * Adding a page: add an entry, then in the page file
 *   export const metadata = createMetadata(pages.pricing)
 * and render <PageJsonLd page={pages.pricing} /> in its body.
 */

type SitemapEntry = MetadataRoute.Sitemap[number]

export type PageEntry = {
  /** Path from the site root, starting with "/". */
  path: string
  /** Page name without the app name, which pageTitle() appends. No colons or dashes as separators. */
  title: string
  /** 120 to 160 characters, written as a direct answer to "what is this page?". */
  description: string
  /** Breadcrumb trail above this page, nearest last. Home is implied. */
  parents?: readonly PageEntry[]
  /** Only set when you know the real date; a fake "now" teaches crawlers to ignore it. */
  lastModified?: SitemapEntry["lastModified"]
  changeFrequency?: SitemapEntry["changeFrequency"]
  priority?: number
  /** Keep out of search results, the sitemap and llms.txt. */
  noIndex?: boolean
  /** Open Graph object type. Articles should also render articleJsonLd. */
  type?: "website" | "article"
  /** Share image path, when this route has its own opengraph-image. */
  image?: string
}

const home = {
  path: "/",
  title: siteConfig.name,
  description: siteConfig.description,
  changeFrequency: "weekly",
  priority: 1,
} satisfies PageEntry

export const pages = {
  home,
  signup: {
    path: "/signup",
    title: "Sign up",
    description: `Create your ${siteConfig.name} account with Google to get started.`,
    changeFrequency: "yearly",
    priority: 0.5,
  },
  login: {
    path: "/login",
    title: "Login",
    description: `Log in to your ${siteConfig.name} account with Google.`,
    changeFrequency: "yearly",
    priority: 0.3,
  },
} satisfies Record<string, PageEntry>

export const publicPages: PageEntry[] = Object.values(pages).filter(
  (page: PageEntry) => !page.noIndex,
)

/**
 * Robots directives for a page. The googlebot line lifts Google's default
 * snippet and preview limits so AI Overviews and rich results can quote and
 * show as much of the page as they need.
 */
export function robotsFor(noIndex = false): Metadata["robots"] {
  if (!isIndexable) return { index: false, follow: false }
  if (noIndex) return { index: false, follow: true }

  return {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  }
}

/*
 * Page titles (the browser tab, search result headline and og:title) are
 * segments joined by a pipe, most specific first and the app name last:
 *   "Acme Inc."                      the home page
 *   "Login | Acme Inc."              a top-level page
 *   "Invoice 42 | Billing | Acme Inc."
 * Never a colon or a dash as the separator. ESLint rejects authored titles
 * that use one; pageTitle() also rewrites them, for titles that come from
 * data (a CMS post called "Launch: what's new" becomes "Launch | what's new").
 */
export const TITLE_SEPARATOR = " | "

function normalizeTitleSegment(segment: string) {
  return segment
    .replace(/\s*:(?=\s|$)/g, TITLE_SEPARATOR)
    .replace(/\s+[-\u2013\u2014\u2015]\s+/g, TITLE_SEPARATOR)
    .replace(/\s*\|\s*/g, TITLE_SEPARATOR)
    .replace(/\s+/g, " ")
    .trim()
}

/** Joins title segments with the pipe separator, app name last. */
export function pageTitle(...segments: string[]) {
  return [...segments, siteConfig.name]
    .map(normalizeTitleSegment)
    .flatMap((segment) => segment.split(TITLE_SEPARATOR))
    .map((segment) => segment.trim())
    .filter((segment, index, all) => segment && all.indexOf(segment) === index)
    .join(TITLE_SEPARATOR)
}

const twitterAccounts = siteConfig.twitterHandle
  ? { site: siteConfig.twitterHandle, creator: siteConfig.twitterHandle }
  : {}

/**
 * The default share card, generated by src/app/opengraph-image.tsx. Listed
 * explicitly because a page that sets its own `openGraph` would otherwise drop
 * the inherited image. A route with its own opengraph-image file still wins
 * for og:image; pass its URL as `image` in the registry to match twitter:image.
 */
export const shareImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${siteConfig.name}: ${siteConfig.description}`,
}

/** Fields every page shares. The root layout spreads this in. */
export const baseOpenGraph = {
  type: "website",
  siteName: siteConfig.name,
  locale: siteConfig.locale,
  images: [shareImage],
} satisfies Metadata["openGraph"]

export const baseTwitter = {
  card: "summary_large_image",
  images: [shareImage],
  ...twitterAccounts,
} satisfies Metadata["twitter"]

/**
 * Builds a page's metadata from its registry entry.
 *
 * Next.js merges metadata shallowly, so a page that sets `openGraph` replaces
 * the root layout's object wholesale. This repeats the shared fields to keep
 * og:site_name, og:locale and twitter:card on every page.
 */
export function createMetadata(page: PageEntry): Metadata {
  const fullTitle = pageTitle(page.title)
  const images = page.image
    ? [{ ...shareImage, url: page.image, alt: fullTitle }]
    : [shareImage]

  return {
    // Absolute so the layout's template cannot add a second app name.
    title: { absolute: fullTitle },
    description: page.description,
    alternates: { canonical: page.path },
    openGraph: {
      ...baseOpenGraph,
      type: page.type ?? "website",
      title: fullTitle,
      description: page.description,
      url: page.path,
      images,
    },
    twitter: {
      ...baseTwitter,
      title: fullTitle,
      description: page.description,
      images,
    },
    robots: robotsFor(page.noIndex),
  }
}
